// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package link_friend

import (
	"bamboo-main/api/link_friend"
)

type ControllerV1 struct{}

func NewV1() link_friend.ILinkFriendV1 {
	return &ControllerV1{}
}
