// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package link_color

import (
	"bamboo-main/api/link_color"
)

type ControllerV1 struct{}

func NewV1() link_color.ILinkColorV1 {
	return &ControllerV1{}
}
