
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      - link: "pgsql:xf_index:123456@tcp(localhost:5432)/xf_index"
        jsonCase: "Snake"
        removePrefix: "xf_"
  default:
    type: "pgsql"
    host: "localhost"
    port: 5432
    dbname: "xf_index"
    user: "xf_index"
    pass: "123456"
    database: "xf_index"
  build:
    name: "main"
    arch: "amd64,arm64,arm"
    system: "darwin,windows,linux"
    packSrc: "resource/public"
    packDst: "internal/packed/build_pack_data.go"
    version: "v0.1.0-beta.1"
    path: "./bin"