
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:new_xiao_main:new_xiao_main@tcp(127.0.0.1:5432)/new_xiao_main"
        descriptionTag: true
        jsonCase: "Snake"
        removePrefix: "xf_"
        gJsonSupport: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app