// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package link_group

import (
	"bamboo-main/api/link_group"
)

type ControllerV1 struct{}

func NewV1() link_group.ILinkGroupV1 {
	return &ControllerV1{}
}
