// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bamboo-main/internal/dao/internal"
)

// linkColorDao is the data access object for the table xf_link_color.
// You can define custom methods on it to extend its functionality as needed.
type linkColorDao struct {
	*internal.LinkColorDao
}

var (
	// LinkColor is a globally accessible object for table xf_link_color operations.
	LinkColor = linkColorDao{internal.NewLinkColorDao()}
)

// Add your custom methods and functionality below.
