// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bamboo-main/internal/dao/internal"
)

// logsDao is the data access object for the table xf_logs.
// You can define custom methods on it to extend its functionality as needed.
type logsDao struct {
	*internal.LogsDao
}

var (
	// Logs is a globally accessible object for table xf_logs operations.
	Logs = logsDao{internal.NewLogsDao()}
)

// Add your custom methods and functionality below.
