// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bamboo-main/internal/dao/internal"
)

// systemDao is the data access object for the table xf_system.
// You can define custom methods on it to extend its functionality as needed.
type systemDao struct {
	*internal.SystemDao
}

var (
	// System is a globally accessible object for table xf_system operations.
	System = systemDao{internal.NewSystemDao()}
)

// Add your custom methods and functionality below.
