// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"develop/internal/dao/internal"
)

// internalXfLogsDao is internal type for wrapping internal DAO implements.
type internalXfLogsDao = *internal.XfLogsDao

// xfLogsDao is the data access object for table xf_logs.
// You can define custom methods on it to extend its functionality as you wish.
type xfLogsDao struct {
	internalXfLogsDao
}

var (
	// XfLogs is globally public accessible object for table xf_logs operations.
	XfLogs = xfLogsDao{
		internal.NewXfLogsDao(),
	}
)

// Fill with you ideas below.
