// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"xiaoMain/internal/dao/internal"
)

// internalXfLinkListDao is internal type for wrapping internal DAO implements.
type internalXfLinkListDao = *internal.XfLinkListDao

// xfLinkListDao is the data access object for table xf_link_list.
// You can define custom methods on it to extend its functionality as you wish.
type xfLinkListDao struct {
	internalXfLinkListDao
}

var (
	// XfLinkList is globally public accessible object for table xf_link_list operations.
	XfLinkList = xfLinkListDao{
		internal.NewXfLinkListDao(),
	}
)

// Fill with you ideas below.
