// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"xiaoMain/internal/dao/internal"
)

// internalXfTokenDao is internal type for wrapping internal DAO implements.
type internalXfTokenDao = *internal.XfTokenDao

// xfTokenDao is the data access object for table xf_token.
// You can define custom methods on it to extend its functionality as you wish.
type xfTokenDao struct {
	internalXfTokenDao
}

var (
	// XfToken is globally public accessible object for table xf_token operations.
	XfToken = xfTokenDao{
		internal.NewXfTokenDao(),
	}
)

// Fill with you ideas below.
