/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthorizationRouteRouteImport } from './routes/_authorization/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminAdminRouteRouteImport } from './routes/_admin/admin/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminSettingRouteImport } from './routes/_admin/admin/setting'
import { Route as AdminAdminSponsorRouteImport } from './routes/_admin/admin/sponsor'
import { Route as AuthorizationAuthLoginRouteImport } from './routes/_authorization/auth/login'
import { Route as AdminAdminLinkIndexRouteImport } from './routes/_admin/admin/link/index'
import { Route as AdminAdminLinkAddRouteImport } from './routes/_admin/admin/link/add'
import { Route as AdminAdminLinkVerifyRouteImport } from './routes/_admin/admin/link/verify'
import { Route as AdminAdminLinkIdEditRouteImport } from './routes/_admin/admin/link/$id.edit'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizationRouteRoute = AuthorizationRouteRouteImport.update({
  id: '/_authorization',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSettingRoute = AdminAdminSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSponsorRoute = AdminAdminSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AuthorizationAuthLoginRoute = AuthorizationAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthorizationRouteRoute,
} as any)
const AdminAdminLinkIndexRoute = AdminAdminLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkAddRoute = AdminAdminLinkAddRouteImport.update({
  id: '/link/add',
  path: '/link/add',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkVerifyRoute = AdminAdminLinkVerifyRouteImport.update({
  id: '/link/verify',
  path: '/link/verify',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkIdEditRoute = AdminAdminLinkIdEditRouteImport.update({
  id: '/link/$id/edit',
  path: '/link/$id/edit',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/setting': typeof AdminAdminSettingRoute
  '/admin/sponsor': typeof AdminAdminSponsorRoute
  '/auth/login': typeof AuthorizationAuthLoginRoute
  '/admin/link/add': typeof AdminAdminLinkAddRoute
  '/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/admin/link/': typeof AdminAdminLinkIndexRoute
  '/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/setting': typeof AdminAdminSettingRoute
  '/admin/sponsor': typeof AdminAdminSponsorRoute
  '/auth/login': typeof AuthorizationAuthLoginRoute
  '/admin/link/add': typeof AdminAdminLinkAddRoute
  '/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/admin/link': typeof AdminAdminLinkIndexRoute
  '/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authorization': typeof AuthorizationRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/setting': typeof AdminAdminSettingRoute
  '/_admin/admin/sponsor': typeof AdminAdminSponsorRoute
  '/_authorization/auth/login': typeof AuthorizationAuthLoginRoute
  '/_admin/admin/link/add': typeof AdminAdminLinkAddRoute
  '/_admin/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/_admin/admin/link/': typeof AdminAdminLinkIndexRoute
  '/_admin/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/setting'
    | '/admin/sponsor'
    | '/auth/login'
    | '/admin/link/add'
    | '/admin/link/verify'
    | '/admin/link/'
    | '/admin/link/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/setting'
    | '/admin/sponsor'
    | '/auth/login'
    | '/admin/link/add'
    | '/admin/link/verify'
    | '/admin/link'
    | '/admin/link/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/_authorization'
    | '/_public'
    | '/_admin/admin'
    | '/_public/'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/setting'
    | '/_admin/admin/sponsor'
    | '/_authorization/auth/login'
    | '/_admin/admin/link/add'
    | '/_admin/admin/link/verify'
    | '/_admin/admin/link/'
    | '/_admin/admin/link/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthorizationRouteRoute: typeof AuthorizationRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorization': {
      id: '/_authorization'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/setting': {
      id: '/_admin/admin/setting'
      path: '/setting'
      fullPath: '/admin/setting'
      preLoaderRoute: typeof AdminAdminSettingRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/sponsor': {
      id: '/_admin/admin/sponsor'
      path: '/sponsor'
      fullPath: '/admin/sponsor'
      preLoaderRoute: typeof AdminAdminSponsorRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_authorization/auth/login': {
      id: '/_authorization/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthorizationAuthLoginRouteImport
      parentRoute: typeof AuthorizationRouteRoute
    }
    '/_admin/admin/link/': {
      id: '/_admin/admin/link/'
      path: '/link'
      fullPath: '/admin/link/'
      preLoaderRoute: typeof AdminAdminLinkIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/add': {
      id: '/_admin/admin/link/add'
      path: '/link/add'
      fullPath: '/admin/link/add'
      preLoaderRoute: typeof AdminAdminLinkAddRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/verify': {
      id: '/_admin/admin/link/verify'
      path: '/link/verify'
      fullPath: '/admin/link/verify'
      preLoaderRoute: typeof AdminAdminLinkVerifyRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/$id/edit': {
      id: '/_admin/admin/link/$id/edit'
      path: '/link/$id/edit'
      fullPath: '/admin/link/$id/edit'
      preLoaderRoute: typeof AdminAdminLinkIdEditRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
  }
}

interface AdminAdminRouteRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminSettingRoute: typeof AdminAdminSettingRoute
  AdminAdminSponsorRoute: typeof AdminAdminSponsorRoute
  AdminAdminLinkAddRoute: typeof AdminAdminLinkAddRoute
  AdminAdminLinkVerifyRoute: typeof AdminAdminLinkVerifyRoute
  AdminAdminLinkIndexRoute: typeof AdminAdminLinkIndexRoute
  AdminAdminLinkIdEditRoute: typeof AdminAdminLinkIdEditRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminSettingRoute: AdminAdminSettingRoute,
  AdminAdminSponsorRoute: AdminAdminSponsorRoute,
  AdminAdminLinkAddRoute: AdminAdminLinkAddRoute,
  AdminAdminLinkVerifyRoute: AdminAdminLinkVerifyRoute,
  AdminAdminLinkIndexRoute: AdminAdminLinkIndexRoute,
  AdminAdminLinkIdEditRoute: AdminAdminLinkIdEditRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthorizationRouteRouteChildren {
  AuthorizationAuthLoginRoute: typeof AuthorizationAuthLoginRoute
}

const AuthorizationRouteRouteChildren: AuthorizationRouteRouteChildren = {
  AuthorizationAuthLoginRoute: AuthorizationAuthLoginRoute,
}

const AuthorizationRouteRouteWithChildren =
  AuthorizationRouteRoute._addFileChildren(AuthorizationRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthorizationRouteRoute: AuthorizationRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
