/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthorizationRouteRouteImport } from './routes/_authorization/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as AdminAdminRouteRouteImport } from './routes/_admin/admin/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutFriendsRouteImport } from './routes/about/friends'
import { Route as AboutMeRouteImport } from './routes/about/me'
import { Route as AboutSponsorRouteImport } from './routes/about/sponsor'
import { Route as AdminAdminColorRouteImport } from './routes/_admin/admin/color'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminLocationRouteImport } from './routes/_admin/admin/location'
import { Route as AdminAdminSettingRouteImport } from './routes/_admin/admin/setting'
import { Route as AdminAdminSponsorRouteImport } from './routes/_admin/admin/sponsor'
import { Route as AuthorizationAuthCallbackRouteImport } from './routes/_authorization/auth/callback'
import { Route as AuthorizationAuthLoginRouteImport } from './routes/_authorization/auth/login'
import { Route as AdminAdminLinkIndexRouteImport } from './routes/_admin/admin/link/index'
import { Route as AdminAdminLinkIdRouteImport } from './routes/_admin/admin/link/$id'
import { Route as AdminAdminLinkAddRouteImport } from './routes/_admin/admin/link/add'
import { Route as AdminAdminLinkVerifyRouteImport } from './routes/_admin/admin/link/verify'
import { Route as AdminAdminLinkIdEditRouteImport } from './routes/_admin/admin/link/$id.edit'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizationRouteRoute = AuthorizationRouteRouteImport.update({
  id: '/_authorization',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutFriendsRoute = AboutFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutSponsorRoute = AboutSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AdminAdminColorRoute = AdminAdminColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLocationRoute = AdminAdminLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSettingRoute = AdminAdminSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSponsorRoute = AdminAdminSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AuthorizationAuthCallbackRoute =
  AuthorizationAuthCallbackRouteImport.update({
    id: '/auth/callback',
    path: '/auth/callback',
    getParentRoute: () => AuthorizationRouteRoute,
  } as any)
const AuthorizationAuthLoginRoute = AuthorizationAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthorizationRouteRoute,
} as any)
const AdminAdminLinkIndexRoute = AdminAdminLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkIdRoute = AdminAdminLinkIdRouteImport.update({
  id: '/link/$id',
  path: '/link/$id',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkAddRoute = AdminAdminLinkAddRouteImport.update({
  id: '/link/add',
  path: '/link/add',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkVerifyRoute = AdminAdminLinkVerifyRouteImport.update({
  id: '/link/verify',
  path: '/link/verify',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkIdEditRoute = AdminAdminLinkIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminAdminLinkIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/about/friends': typeof AboutFriendsRoute
  '/about/me': typeof AboutMeRoute
  '/about/sponsor': typeof AboutSponsorRoute
  '/about/': typeof AboutIndexRoute
  '/admin/color': typeof AdminAdminColorRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/location': typeof AdminAdminLocationRoute
  '/admin/setting': typeof AdminAdminSettingRoute
  '/admin/sponsor': typeof AdminAdminSponsorRoute
  '/auth/callback': typeof AuthorizationAuthCallbackRoute
  '/auth/login': typeof AuthorizationAuthLoginRoute
  '/admin/link/$id': typeof AdminAdminLinkIdRouteWithChildren
  '/admin/link/add': typeof AdminAdminLinkAddRoute
  '/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/admin/link/': typeof AdminAdminLinkIndexRoute
  '/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/about/friends': typeof AboutFriendsRoute
  '/about/me': typeof AboutMeRoute
  '/about/sponsor': typeof AboutSponsorRoute
  '/about': typeof AboutIndexRoute
  '/admin/color': typeof AdminAdminColorRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/location': typeof AdminAdminLocationRoute
  '/admin/setting': typeof AdminAdminSettingRoute
  '/admin/sponsor': typeof AdminAdminSponsorRoute
  '/auth/callback': typeof AuthorizationAuthCallbackRoute
  '/auth/login': typeof AuthorizationAuthLoginRoute
  '/admin/link/$id': typeof AdminAdminLinkIdRouteWithChildren
  '/admin/link/add': typeof AdminAdminLinkAddRoute
  '/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/admin/link': typeof AdminAdminLinkIndexRoute
  '/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authorization': typeof AuthorizationRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/about': typeof AboutRouteRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteRouteWithChildren
  '/about/friends': typeof AboutFriendsRoute
  '/about/me': typeof AboutMeRoute
  '/about/sponsor': typeof AboutSponsorRoute
  '/_public/': typeof PublicIndexRoute
  '/about/': typeof AboutIndexRoute
  '/_admin/admin/color': typeof AdminAdminColorRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/location': typeof AdminAdminLocationRoute
  '/_admin/admin/setting': typeof AdminAdminSettingRoute
  '/_admin/admin/sponsor': typeof AdminAdminSponsorRoute
  '/_authorization/auth/callback': typeof AuthorizationAuthCallbackRoute
  '/_authorization/auth/login': typeof AuthorizationAuthLoginRoute
  '/_admin/admin/link/$id': typeof AdminAdminLinkIdRouteWithChildren
  '/_admin/admin/link/add': typeof AdminAdminLinkAddRoute
  '/_admin/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/_admin/admin/link/': typeof AdminAdminLinkIndexRoute
  '/_admin/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/about/friends'
    | '/about/me'
    | '/about/sponsor'
    | '/about/'
    | '/admin/color'
    | '/admin/dashboard'
    | '/admin/location'
    | '/admin/setting'
    | '/admin/sponsor'
    | '/auth/callback'
    | '/auth/login'
    | '/admin/link/$id'
    | '/admin/link/add'
    | '/admin/link/verify'
    | '/admin/link/'
    | '/admin/link/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about/friends'
    | '/about/me'
    | '/about/sponsor'
    | '/about'
    | '/admin/color'
    | '/admin/dashboard'
    | '/admin/location'
    | '/admin/setting'
    | '/admin/sponsor'
    | '/auth/callback'
    | '/auth/login'
    | '/admin/link/$id'
    | '/admin/link/add'
    | '/admin/link/verify'
    | '/admin/link'
    | '/admin/link/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/_authorization'
    | '/_public'
    | '/about'
    | '/_admin/admin'
    | '/about/friends'
    | '/about/me'
    | '/about/sponsor'
    | '/_public/'
    | '/about/'
    | '/_admin/admin/color'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/location'
    | '/_admin/admin/setting'
    | '/_admin/admin/sponsor'
    | '/_authorization/auth/callback'
    | '/_authorization/auth/login'
    | '/_admin/admin/link/$id'
    | '/_admin/admin/link/add'
    | '/_admin/admin/link/verify'
    | '/_admin/admin/link/'
    | '/_admin/admin/link/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthorizationRouteRoute: typeof AuthorizationRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorization': {
      id: '/_authorization'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/friends': {
      id: '/about/friends'
      path: '/friends'
      fullPath: '/about/friends'
      preLoaderRoute: typeof AboutFriendsRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/me': {
      id: '/about/me'
      path: '/me'
      fullPath: '/about/me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/sponsor': {
      id: '/about/sponsor'
      path: '/sponsor'
      fullPath: '/about/sponsor'
      preLoaderRoute: typeof AboutSponsorRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/_admin/admin/color': {
      id: '/_admin/admin/color'
      path: '/color'
      fullPath: '/admin/color'
      preLoaderRoute: typeof AdminAdminColorRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/location': {
      id: '/_admin/admin/location'
      path: '/location'
      fullPath: '/admin/location'
      preLoaderRoute: typeof AdminAdminLocationRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/setting': {
      id: '/_admin/admin/setting'
      path: '/setting'
      fullPath: '/admin/setting'
      preLoaderRoute: typeof AdminAdminSettingRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/sponsor': {
      id: '/_admin/admin/sponsor'
      path: '/sponsor'
      fullPath: '/admin/sponsor'
      preLoaderRoute: typeof AdminAdminSponsorRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_authorization/auth/callback': {
      id: '/_authorization/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthorizationAuthCallbackRouteImport
      parentRoute: typeof AuthorizationRouteRoute
    }
    '/_authorization/auth/login': {
      id: '/_authorization/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthorizationAuthLoginRouteImport
      parentRoute: typeof AuthorizationRouteRoute
    }
    '/_admin/admin/link/': {
      id: '/_admin/admin/link/'
      path: '/link'
      fullPath: '/admin/link/'
      preLoaderRoute: typeof AdminAdminLinkIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/$id': {
      id: '/_admin/admin/link/$id'
      path: '/link/$id'
      fullPath: '/admin/link/$id'
      preLoaderRoute: typeof AdminAdminLinkIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/add': {
      id: '/_admin/admin/link/add'
      path: '/link/add'
      fullPath: '/admin/link/add'
      preLoaderRoute: typeof AdminAdminLinkAddRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/verify': {
      id: '/_admin/admin/link/verify'
      path: '/link/verify'
      fullPath: '/admin/link/verify'
      preLoaderRoute: typeof AdminAdminLinkVerifyRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/$id/edit': {
      id: '/_admin/admin/link/$id/edit'
      path: '/edit'
      fullPath: '/admin/link/$id/edit'
      preLoaderRoute: typeof AdminAdminLinkIdEditRouteImport
      parentRoute: typeof AdminAdminLinkIdRoute
    }
  }
}

interface AdminAdminLinkIdRouteChildren {
  AdminAdminLinkIdEditRoute: typeof AdminAdminLinkIdEditRoute
}

const AdminAdminLinkIdRouteChildren: AdminAdminLinkIdRouteChildren = {
  AdminAdminLinkIdEditRoute: AdminAdminLinkIdEditRoute,
}

const AdminAdminLinkIdRouteWithChildren =
  AdminAdminLinkIdRoute._addFileChildren(AdminAdminLinkIdRouteChildren)

interface AdminAdminRouteRouteChildren {
  AdminAdminColorRoute: typeof AdminAdminColorRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminLocationRoute: typeof AdminAdminLocationRoute
  AdminAdminSettingRoute: typeof AdminAdminSettingRoute
  AdminAdminSponsorRoute: typeof AdminAdminSponsorRoute
  AdminAdminLinkIdRoute: typeof AdminAdminLinkIdRouteWithChildren
  AdminAdminLinkAddRoute: typeof AdminAdminLinkAddRoute
  AdminAdminLinkVerifyRoute: typeof AdminAdminLinkVerifyRoute
  AdminAdminLinkIndexRoute: typeof AdminAdminLinkIndexRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminColorRoute: AdminAdminColorRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminLocationRoute: AdminAdminLocationRoute,
  AdminAdminSettingRoute: AdminAdminSettingRoute,
  AdminAdminSponsorRoute: AdminAdminSponsorRoute,
  AdminAdminLinkIdRoute: AdminAdminLinkIdRouteWithChildren,
  AdminAdminLinkAddRoute: AdminAdminLinkAddRoute,
  AdminAdminLinkVerifyRoute: AdminAdminLinkVerifyRoute,
  AdminAdminLinkIndexRoute: AdminAdminLinkIndexRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthorizationRouteRouteChildren {
  AuthorizationAuthCallbackRoute: typeof AuthorizationAuthCallbackRoute
  AuthorizationAuthLoginRoute: typeof AuthorizationAuthLoginRoute
}

const AuthorizationRouteRouteChildren: AuthorizationRouteRouteChildren = {
  AuthorizationAuthCallbackRoute: AuthorizationAuthCallbackRoute,
  AuthorizationAuthLoginRoute: AuthorizationAuthLoginRoute,
}

const AuthorizationRouteRouteWithChildren =
  AuthorizationRouteRoute._addFileChildren(AuthorizationRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AboutRouteRouteChildren {
  AboutFriendsRoute: typeof AboutFriendsRoute
  AboutMeRoute: typeof AboutMeRoute
  AboutSponsorRoute: typeof AboutSponsorRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutFriendsRoute: AboutFriendsRoute,
  AboutMeRoute: AboutMeRoute,
  AboutSponsorRoute: AboutSponsorRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthorizationRouteRoute: AuthorizationRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AboutRouteRoute: AboutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
