/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthorizationRouteRouteImport } from './routes/_authorization/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as OperateRouteRouteImport } from './routes/operate/route'
import { Route as AdminAdminRouteRouteImport } from './routes/_admin/admin/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as UserUserRouteRouteImport } from './routes/_user/user/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutFriendsRouteImport } from './routes/about/friends'
import { Route as AboutMeRouteImport } from './routes/about/me'
import { Route as AboutSponsorRouteImport } from './routes/about/sponsor'
import { Route as OperateIndexRouteImport } from './routes/operate/index'
import { Route as OperateApplyRouteImport } from './routes/operate/apply'
import { Route as OperateSponsorRouteImport } from './routes/operate/sponsor'
import { Route as AdminAdminColorRouteImport } from './routes/_admin/admin/color'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminLocationRouteImport } from './routes/_admin/admin/location'
import { Route as AdminAdminRankingRouteImport } from './routes/_admin/admin/ranking'
import { Route as AdminAdminSettingRouteImport } from './routes/_admin/admin/setting'
import { Route as AdminAdminSponsorRouteImport } from './routes/_admin/admin/sponsor'
import { Route as AuthorizationAuthCallbackRouteImport } from './routes/_authorization/auth/callback'
import { Route as AuthorizationAuthLoginRouteImport } from './routes/_authorization/auth/login'
import { Route as AuthorizationAuthRegisterRouteImport } from './routes/_authorization/auth/register'
import { Route as UserUserAccountRouteImport } from './routes/_user/user/account'
import { Route as UserUserDashboardRouteImport } from './routes/_user/user/dashboard'
import { Route as AdminAdminLinkIndexRouteImport } from './routes/_admin/admin/link/index'
import { Route as AdminAdminLinkAddRouteImport } from './routes/_admin/admin/link/add'
import { Route as AdminAdminLinkAnomalyRouteImport } from './routes/_admin/admin/link/anomaly'
import { Route as AdminAdminLinkVerifyRouteImport } from './routes/_admin/admin/link/verify'
import { Route as AdminAdminSponsorVerifyRouteImport } from './routes/_admin/admin/sponsor/verify'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as UserUserLinksIndexRouteImport } from './routes/_user/user/links/index'
import { Route as UserUserSponsorsIndexRouteImport } from './routes/_user/user/sponsors/index'
import { Route as AdminAdminLinkIdIndexRouteImport } from './routes/_admin/admin/link/$id/index'
import { Route as AdminAdminLinkIdEditRouteImport } from './routes/_admin/admin/link/$id/edit'
import { Route as UserUserLinksIdEditRouteImport } from './routes/_user/user/links/$id/edit'
import { Route as UserUserLinksIdEditLocationRouteImport } from './routes/_user/user/links/$id/edit-location'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizationRouteRoute = AuthorizationRouteRouteImport.update({
  id: '/_authorization',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateRouteRoute = OperateRouteRouteImport.update({
  id: '/operate',
  path: '/operate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const UserUserRouteRoute = UserUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => UserRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutFriendsRoute = AboutFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutSponsorRoute = AboutSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => AboutRouteRoute,
} as any)
const OperateIndexRoute = OperateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperateRouteRoute,
} as any)
const OperateApplyRoute = OperateApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => OperateRouteRoute,
} as any)
const OperateSponsorRoute = OperateSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => OperateRouteRoute,
} as any)
const AdminAdminColorRoute = AdminAdminColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLocationRoute = AdminAdminLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminRankingRoute = AdminAdminRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSettingRoute = AdminAdminSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSponsorRoute = AdminAdminSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AuthorizationAuthCallbackRoute =
  AuthorizationAuthCallbackRouteImport.update({
    id: '/auth/callback',
    path: '/auth/callback',
    getParentRoute: () => AuthorizationRouteRoute,
  } as any)
const AuthorizationAuthLoginRoute = AuthorizationAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthorizationRouteRoute,
} as any)
const AuthorizationAuthRegisterRoute =
  AuthorizationAuthRegisterRouteImport.update({
    id: '/auth/register',
    path: '/auth/register',
    getParentRoute: () => AuthorizationRouteRoute,
  } as any)
const UserUserAccountRoute = UserUserAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => UserUserRouteRoute,
} as any)
const UserUserDashboardRoute = UserUserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserUserRouteRoute,
} as any)
const AdminAdminLinkIndexRoute = AdminAdminLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkAddRoute = AdminAdminLinkAddRouteImport.update({
  id: '/link/add',
  path: '/link/add',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkAnomalyRoute = AdminAdminLinkAnomalyRouteImport.update({
  id: '/link/anomaly',
  path: '/link/anomaly',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkVerifyRoute = AdminAdminLinkVerifyRouteImport.update({
  id: '/link/verify',
  path: '/link/verify',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSponsorVerifyRoute = AdminAdminSponsorVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminAdminSponsorRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const UserUserLinksIndexRoute = UserUserLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => UserUserRouteRoute,
} as any)
const UserUserSponsorsIndexRoute = UserUserSponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => UserUserRouteRoute,
} as any)
const AdminAdminLinkIdIndexRoute = AdminAdminLinkIdIndexRouteImport.update({
  id: '/link/$id/',
  path: '/link/$id/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLinkIdEditRoute = AdminAdminLinkIdEditRouteImport.update({
  id: '/link/$id/edit',
  path: '/link/$id/edit',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const UserUserLinksIdEditRoute = UserUserLinksIdEditRouteImport.update({
  id: '/links/$id/edit',
  path: '/links/$id/edit',
  getParentRoute: () => UserUserRouteRoute,
} as any)
const UserUserLinksIdEditLocationRoute =
  UserUserLinksIdEditLocationRouteImport.update({
    id: '/links/$id/edit-location',
    path: '/links/$id/edit-location',
    getParentRoute: () => UserUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/operate': typeof OperateRouteRouteWithChildren
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/user': typeof UserUserRouteRouteWithChildren
  '/about/friends': typeof AboutFriendsRoute
  '/about/me': typeof AboutMeRoute
  '/about/sponsor': typeof AboutSponsorRoute
  '/operate/apply': typeof OperateApplyRoute
  '/operate/sponsor': typeof OperateSponsorRoute
  '/about/': typeof AboutIndexRoute
  '/operate/': typeof OperateIndexRoute
  '/admin/color': typeof AdminAdminColorRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/location': typeof AdminAdminLocationRoute
  '/admin/ranking': typeof AdminAdminRankingRoute
  '/admin/setting': typeof AdminAdminSettingRoute
  '/admin/sponsor': typeof AdminAdminSponsorRouteWithChildren
  '/auth/callback': typeof AuthorizationAuthCallbackRoute
  '/auth/login': typeof AuthorizationAuthLoginRoute
  '/auth/register': typeof AuthorizationAuthRegisterRoute
  '/user/account': typeof UserUserAccountRoute
  '/user/dashboard': typeof UserUserDashboardRoute
  '/admin/link/add': typeof AdminAdminLinkAddRoute
  '/admin/link/anomaly': typeof AdminAdminLinkAnomalyRoute
  '/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/admin/sponsor/verify': typeof AdminAdminSponsorVerifyRoute
  '/admin/link/': typeof AdminAdminLinkIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
  '/user/links/': typeof UserUserLinksIndexRoute
  '/user/sponsors/': typeof UserUserSponsorsIndexRoute
  '/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
  '/user/links/$id/edit': typeof UserUserLinksIdEditRoute
  '/user/links/$id/edit-location': typeof UserUserLinksIdEditLocationRoute
  '/admin/link/$id/': typeof AdminAdminLinkIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/user': typeof UserUserRouteRouteWithChildren
  '/about/friends': typeof AboutFriendsRoute
  '/about/me': typeof AboutMeRoute
  '/about/sponsor': typeof AboutSponsorRoute
  '/operate/apply': typeof OperateApplyRoute
  '/operate/sponsor': typeof OperateSponsorRoute
  '/about': typeof AboutIndexRoute
  '/operate': typeof OperateIndexRoute
  '/admin/color': typeof AdminAdminColorRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/location': typeof AdminAdminLocationRoute
  '/admin/ranking': typeof AdminAdminRankingRoute
  '/admin/setting': typeof AdminAdminSettingRoute
  '/admin/sponsor': typeof AdminAdminSponsorRouteWithChildren
  '/auth/callback': typeof AuthorizationAuthCallbackRoute
  '/auth/login': typeof AuthorizationAuthLoginRoute
  '/auth/register': typeof AuthorizationAuthRegisterRoute
  '/user/account': typeof UserUserAccountRoute
  '/user/dashboard': typeof UserUserDashboardRoute
  '/admin/link/add': typeof AdminAdminLinkAddRoute
  '/admin/link/anomaly': typeof AdminAdminLinkAnomalyRoute
  '/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/admin/sponsor/verify': typeof AdminAdminSponsorVerifyRoute
  '/admin/link': typeof AdminAdminLinkIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/user/links': typeof UserUserLinksIndexRoute
  '/user/sponsors': typeof UserUserSponsorsIndexRoute
  '/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
  '/user/links/$id/edit': typeof UserUserLinksIdEditRoute
  '/user/links/$id/edit-location': typeof UserUserLinksIdEditLocationRoute
  '/admin/link/$id': typeof AdminAdminLinkIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authorization': typeof AuthorizationRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/about': typeof AboutRouteRouteWithChildren
  '/operate': typeof OperateRouteRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteRouteWithChildren
  '/_user/user': typeof UserUserRouteRouteWithChildren
  '/about/friends': typeof AboutFriendsRoute
  '/about/me': typeof AboutMeRoute
  '/about/sponsor': typeof AboutSponsorRoute
  '/operate/apply': typeof OperateApplyRoute
  '/operate/sponsor': typeof OperateSponsorRoute
  '/_public/': typeof PublicIndexRoute
  '/about/': typeof AboutIndexRoute
  '/operate/': typeof OperateIndexRoute
  '/_admin/admin/color': typeof AdminAdminColorRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/location': typeof AdminAdminLocationRoute
  '/_admin/admin/ranking': typeof AdminAdminRankingRoute
  '/_admin/admin/setting': typeof AdminAdminSettingRoute
  '/_admin/admin/sponsor': typeof AdminAdminSponsorRouteWithChildren
  '/_authorization/auth/callback': typeof AuthorizationAuthCallbackRoute
  '/_authorization/auth/login': typeof AuthorizationAuthLoginRoute
  '/_authorization/auth/register': typeof AuthorizationAuthRegisterRoute
  '/_user/user/account': typeof UserUserAccountRoute
  '/_user/user/dashboard': typeof UserUserDashboardRoute
  '/_admin/admin/link/add': typeof AdminAdminLinkAddRoute
  '/_admin/admin/link/anomaly': typeof AdminAdminLinkAnomalyRoute
  '/_admin/admin/link/verify': typeof AdminAdminLinkVerifyRoute
  '/_admin/admin/sponsor/verify': typeof AdminAdminSponsorVerifyRoute
  '/_admin/admin/link/': typeof AdminAdminLinkIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
  '/_user/user/links/': typeof UserUserLinksIndexRoute
  '/_user/user/sponsors/': typeof UserUserSponsorsIndexRoute
  '/_admin/admin/link/$id/edit': typeof AdminAdminLinkIdEditRoute
  '/_user/user/links/$id/edit': typeof UserUserLinksIdEditRoute
  '/_user/user/links/$id/edit-location': typeof UserUserLinksIdEditLocationRoute
  '/_admin/admin/link/$id/': typeof AdminAdminLinkIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/operate'
    | '/admin'
    | '/user'
    | '/about/friends'
    | '/about/me'
    | '/about/sponsor'
    | '/operate/apply'
    | '/operate/sponsor'
    | '/about/'
    | '/operate/'
    | '/admin/color'
    | '/admin/dashboard'
    | '/admin/location'
    | '/admin/ranking'
    | '/admin/setting'
    | '/admin/sponsor'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/user/account'
    | '/user/dashboard'
    | '/admin/link/add'
    | '/admin/link/anomaly'
    | '/admin/link/verify'
    | '/admin/sponsor/verify'
    | '/admin/link/'
    | '/admin/users/'
    | '/user/links/'
    | '/user/sponsors/'
    | '/admin/link/$id/edit'
    | '/user/links/$id/edit'
    | '/user/links/$id/edit-location'
    | '/admin/link/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/user'
    | '/about/friends'
    | '/about/me'
    | '/about/sponsor'
    | '/operate/apply'
    | '/operate/sponsor'
    | '/about'
    | '/operate'
    | '/admin/color'
    | '/admin/dashboard'
    | '/admin/location'
    | '/admin/ranking'
    | '/admin/setting'
    | '/admin/sponsor'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/user/account'
    | '/user/dashboard'
    | '/admin/link/add'
    | '/admin/link/anomaly'
    | '/admin/link/verify'
    | '/admin/sponsor/verify'
    | '/admin/link'
    | '/admin/users'
    | '/user/links'
    | '/user/sponsors'
    | '/admin/link/$id/edit'
    | '/user/links/$id/edit'
    | '/user/links/$id/edit-location'
    | '/admin/link/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_authorization'
    | '/_public'
    | '/_user'
    | '/about'
    | '/operate'
    | '/_admin/admin'
    | '/_user/user'
    | '/about/friends'
    | '/about/me'
    | '/about/sponsor'
    | '/operate/apply'
    | '/operate/sponsor'
    | '/_public/'
    | '/about/'
    | '/operate/'
    | '/_admin/admin/color'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/location'
    | '/_admin/admin/ranking'
    | '/_admin/admin/setting'
    | '/_admin/admin/sponsor'
    | '/_authorization/auth/callback'
    | '/_authorization/auth/login'
    | '/_authorization/auth/register'
    | '/_user/user/account'
    | '/_user/user/dashboard'
    | '/_admin/admin/link/add'
    | '/_admin/admin/link/anomaly'
    | '/_admin/admin/link/verify'
    | '/_admin/admin/sponsor/verify'
    | '/_admin/admin/link/'
    | '/_admin/admin/users/'
    | '/_user/user/links/'
    | '/_user/user/sponsors/'
    | '/_admin/admin/link/$id/edit'
    | '/_user/user/links/$id/edit'
    | '/_user/user/links/$id/edit-location'
    | '/_admin/admin/link/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthorizationRouteRoute: typeof AuthorizationRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  OperateRouteRoute: typeof OperateRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorization': {
      id: '/_authorization'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate': {
      id: '/operate'
      path: '/operate'
      fullPath: '/operate'
      preLoaderRoute: typeof OperateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_user/user': {
      id: '/_user/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserUserRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/friends': {
      id: '/about/friends'
      path: '/friends'
      fullPath: '/about/friends'
      preLoaderRoute: typeof AboutFriendsRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/me': {
      id: '/about/me'
      path: '/me'
      fullPath: '/about/me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/sponsor': {
      id: '/about/sponsor'
      path: '/sponsor'
      fullPath: '/about/sponsor'
      preLoaderRoute: typeof AboutSponsorRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/operate/': {
      id: '/operate/'
      path: '/'
      fullPath: '/operate/'
      preLoaderRoute: typeof OperateIndexRouteImport
      parentRoute: typeof OperateRouteRoute
    }
    '/operate/apply': {
      id: '/operate/apply'
      path: '/apply'
      fullPath: '/operate/apply'
      preLoaderRoute: typeof OperateApplyRouteImport
      parentRoute: typeof OperateRouteRoute
    }
    '/operate/sponsor': {
      id: '/operate/sponsor'
      path: '/sponsor'
      fullPath: '/operate/sponsor'
      preLoaderRoute: typeof OperateSponsorRouteImport
      parentRoute: typeof OperateRouteRoute
    }
    '/_admin/admin/color': {
      id: '/_admin/admin/color'
      path: '/color'
      fullPath: '/admin/color'
      preLoaderRoute: typeof AdminAdminColorRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/location': {
      id: '/_admin/admin/location'
      path: '/location'
      fullPath: '/admin/location'
      preLoaderRoute: typeof AdminAdminLocationRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/ranking': {
      id: '/_admin/admin/ranking'
      path: '/ranking'
      fullPath: '/admin/ranking'
      preLoaderRoute: typeof AdminAdminRankingRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/setting': {
      id: '/_admin/admin/setting'
      path: '/setting'
      fullPath: '/admin/setting'
      preLoaderRoute: typeof AdminAdminSettingRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/sponsor': {
      id: '/_admin/admin/sponsor'
      path: '/sponsor'
      fullPath: '/admin/sponsor'
      preLoaderRoute: typeof AdminAdminSponsorRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_authorization/auth/callback': {
      id: '/_authorization/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthorizationAuthCallbackRouteImport
      parentRoute: typeof AuthorizationRouteRoute
    }
    '/_authorization/auth/login': {
      id: '/_authorization/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthorizationAuthLoginRouteImport
      parentRoute: typeof AuthorizationRouteRoute
    }
    '/_authorization/auth/register': {
      id: '/_authorization/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthorizationAuthRegisterRouteImport
      parentRoute: typeof AuthorizationRouteRoute
    }
    '/_user/user/account': {
      id: '/_user/user/account'
      path: '/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof UserUserAccountRouteImport
      parentRoute: typeof UserUserRouteRoute
    }
    '/_user/user/dashboard': {
      id: '/_user/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserUserDashboardRouteImport
      parentRoute: typeof UserUserRouteRoute
    }
    '/_admin/admin/link/': {
      id: '/_admin/admin/link/'
      path: '/link'
      fullPath: '/admin/link/'
      preLoaderRoute: typeof AdminAdminLinkIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/add': {
      id: '/_admin/admin/link/add'
      path: '/link/add'
      fullPath: '/admin/link/add'
      preLoaderRoute: typeof AdminAdminLinkAddRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/anomaly': {
      id: '/_admin/admin/link/anomaly'
      path: '/link/anomaly'
      fullPath: '/admin/link/anomaly'
      preLoaderRoute: typeof AdminAdminLinkAnomalyRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/verify': {
      id: '/_admin/admin/link/verify'
      path: '/link/verify'
      fullPath: '/admin/link/verify'
      preLoaderRoute: typeof AdminAdminLinkVerifyRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/sponsor/verify': {
      id: '/_admin/admin/sponsor/verify'
      path: '/verify'
      fullPath: '/admin/sponsor/verify'
      preLoaderRoute: typeof AdminAdminSponsorVerifyRouteImport
      parentRoute: typeof AdminAdminSponsorRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_user/user/links/': {
      id: '/_user/user/links/'
      path: '/links'
      fullPath: '/user/links/'
      preLoaderRoute: typeof UserUserLinksIndexRouteImport
      parentRoute: typeof UserUserRouteRoute
    }
    '/_user/user/sponsors/': {
      id: '/_user/user/sponsors/'
      path: '/sponsors'
      fullPath: '/user/sponsors/'
      preLoaderRoute: typeof UserUserSponsorsIndexRouteImport
      parentRoute: typeof UserUserRouteRoute
    }
    '/_admin/admin/link/$id/': {
      id: '/_admin/admin/link/$id/'
      path: '/link/$id'
      fullPath: '/admin/link/$id/'
      preLoaderRoute: typeof AdminAdminLinkIdIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/link/$id/edit': {
      id: '/_admin/admin/link/$id/edit'
      path: '/link/$id/edit'
      fullPath: '/admin/link/$id/edit'
      preLoaderRoute: typeof AdminAdminLinkIdEditRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_user/user/links/$id/edit': {
      id: '/_user/user/links/$id/edit'
      path: '/links/$id/edit'
      fullPath: '/user/links/$id/edit'
      preLoaderRoute: typeof UserUserLinksIdEditRouteImport
      parentRoute: typeof UserUserRouteRoute
    }
    '/_user/user/links/$id/edit-location': {
      id: '/_user/user/links/$id/edit-location'
      path: '/links/$id/edit-location'
      fullPath: '/user/links/$id/edit-location'
      preLoaderRoute: typeof UserUserLinksIdEditLocationRouteImport
      parentRoute: typeof UserUserRouteRoute
    }
  }
}

interface AdminAdminSponsorRouteChildren {
  AdminAdminSponsorVerifyRoute: typeof AdminAdminSponsorVerifyRoute
}

const AdminAdminSponsorRouteChildren: AdminAdminSponsorRouteChildren = {
  AdminAdminSponsorVerifyRoute: AdminAdminSponsorVerifyRoute,
}

const AdminAdminSponsorRouteWithChildren =
  AdminAdminSponsorRoute._addFileChildren(AdminAdminSponsorRouteChildren)

interface AdminAdminRouteRouteChildren {
  AdminAdminColorRoute: typeof AdminAdminColorRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminLocationRoute: typeof AdminAdminLocationRoute
  AdminAdminRankingRoute: typeof AdminAdminRankingRoute
  AdminAdminSettingRoute: typeof AdminAdminSettingRoute
  AdminAdminSponsorRoute: typeof AdminAdminSponsorRouteWithChildren
  AdminAdminLinkAddRoute: typeof AdminAdminLinkAddRoute
  AdminAdminLinkAnomalyRoute: typeof AdminAdminLinkAnomalyRoute
  AdminAdminLinkVerifyRoute: typeof AdminAdminLinkVerifyRoute
  AdminAdminLinkIndexRoute: typeof AdminAdminLinkIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
  AdminAdminLinkIdEditRoute: typeof AdminAdminLinkIdEditRoute
  AdminAdminLinkIdIndexRoute: typeof AdminAdminLinkIdIndexRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminColorRoute: AdminAdminColorRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminLocationRoute: AdminAdminLocationRoute,
  AdminAdminRankingRoute: AdminAdminRankingRoute,
  AdminAdminSettingRoute: AdminAdminSettingRoute,
  AdminAdminSponsorRoute: AdminAdminSponsorRouteWithChildren,
  AdminAdminLinkAddRoute: AdminAdminLinkAddRoute,
  AdminAdminLinkAnomalyRoute: AdminAdminLinkAnomalyRoute,
  AdminAdminLinkVerifyRoute: AdminAdminLinkVerifyRoute,
  AdminAdminLinkIndexRoute: AdminAdminLinkIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
  AdminAdminLinkIdEditRoute: AdminAdminLinkIdEditRoute,
  AdminAdminLinkIdIndexRoute: AdminAdminLinkIdIndexRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthorizationRouteRouteChildren {
  AuthorizationAuthCallbackRoute: typeof AuthorizationAuthCallbackRoute
  AuthorizationAuthLoginRoute: typeof AuthorizationAuthLoginRoute
  AuthorizationAuthRegisterRoute: typeof AuthorizationAuthRegisterRoute
}

const AuthorizationRouteRouteChildren: AuthorizationRouteRouteChildren = {
  AuthorizationAuthCallbackRoute: AuthorizationAuthCallbackRoute,
  AuthorizationAuthLoginRoute: AuthorizationAuthLoginRoute,
  AuthorizationAuthRegisterRoute: AuthorizationAuthRegisterRoute,
}

const AuthorizationRouteRouteWithChildren =
  AuthorizationRouteRoute._addFileChildren(AuthorizationRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserUserRouteRouteChildren {
  UserUserAccountRoute: typeof UserUserAccountRoute
  UserUserDashboardRoute: typeof UserUserDashboardRoute
  UserUserLinksIndexRoute: typeof UserUserLinksIndexRoute
  UserUserSponsorsIndexRoute: typeof UserUserSponsorsIndexRoute
  UserUserLinksIdEditRoute: typeof UserUserLinksIdEditRoute
  UserUserLinksIdEditLocationRoute: typeof UserUserLinksIdEditLocationRoute
}

const UserUserRouteRouteChildren: UserUserRouteRouteChildren = {
  UserUserAccountRoute: UserUserAccountRoute,
  UserUserDashboardRoute: UserUserDashboardRoute,
  UserUserLinksIndexRoute: UserUserLinksIndexRoute,
  UserUserSponsorsIndexRoute: UserUserSponsorsIndexRoute,
  UserUserLinksIdEditRoute: UserUserLinksIdEditRoute,
  UserUserLinksIdEditLocationRoute: UserUserLinksIdEditLocationRoute,
}

const UserUserRouteRouteWithChildren = UserUserRouteRoute._addFileChildren(
  UserUserRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserUserRouteRoute: typeof UserUserRouteRouteWithChildren
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserUserRouteRoute: UserUserRouteRouteWithChildren,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AboutRouteRouteChildren {
  AboutFriendsRoute: typeof AboutFriendsRoute
  AboutMeRoute: typeof AboutMeRoute
  AboutSponsorRoute: typeof AboutSponsorRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutFriendsRoute: AboutFriendsRoute,
  AboutMeRoute: AboutMeRoute,
  AboutSponsorRoute: AboutSponsorRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

interface OperateRouteRouteChildren {
  OperateApplyRoute: typeof OperateApplyRoute
  OperateSponsorRoute: typeof OperateSponsorRoute
  OperateIndexRoute: typeof OperateIndexRoute
}

const OperateRouteRouteChildren: OperateRouteRouteChildren = {
  OperateApplyRoute: OperateApplyRoute,
  OperateSponsorRoute: OperateSponsorRoute,
  OperateIndexRoute: OperateIndexRoute,
}

const OperateRouteRouteWithChildren = OperateRouteRoute._addFileChildren(
  OperateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthorizationRouteRoute: AuthorizationRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  OperateRouteRoute: OperateRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
