// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package apply

import (
	"bamboo-main/api/apply"
	"bamboo-main/internal/service"
)

type ControllerV1 struct {
	iFriend service.IFriend
	iColor  service.IColor
	iGroup  service.IGroup
	iApply  service.IApply
	iEmail  service.IEmail
}

func NewV1() apply.IApplyV1 {
	return &ControllerV1{
		iFriend: service.Friend(),
		iColor:  service.Color(),
		iGroup:  service.Group(),
		iApply:  service.Apply(),
		iEmail:  service.Email(),
	}
}
