// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package link

import (
	"xiaoMain/api/link"
)

type ControllerV1 struct{}

func NewV1() link.ILinkV1 {
	return &ControllerV1{}
}
